### ISSUE TITLE
Error when using a lambda function as masking_method in ZNormalization

### ISSUE THREAD

**Issue by arthursw** [fepegar/torchio#1051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

The transform `tio.ZNormalization(masking_method=lambda x: x > x.mean())` does not work when using it with a dataloader (same with ` lambda x: x>0`).

Strangely, it works when using it independently, as in the following example.

### Code for reproduction

```python
#%%
from pathlib import Path
import torch
import torchio as tio
import multiprocessing
import lovely_tensors as lt
lt.monkey_patch()

#%% Works:

flair = tio.ScalarImage('/data/flair_raw.nii.gz')
norm = tio.ZNormalization(masking_method=lambda x: x > 0)
flair = norm(flair)
flair.save('/data/flair_normalized.nii.gz')

#%% Does not work:

seed = 42 
num_workers = multiprocessing.cpu_count() // 2
subject_paths = list(Path('/data/flair/').iterdir())

training_subjects = []
for subject_path in subject_paths:
	subject = tio.Subject(
		flair=tio.ScalarImage(subject_path / 'flair.nii.gz'),
		segmentation=tio.LabelMap(subject_path / 'seg.nii.gz'),
	)
	training_subjects.append(subject)

training_transform = tio.Compose([
	tio.ZNormalization(masking_method=lambda x: x>0),
	# tio.ZNormalization(masking_method=tio.ZNormalization.mean),
	tio.OneHot(num_classes=2),
])

training_batch_size = 2
patch_size = (48, 128, 496)
training_set = tio.SubjectsDataset(training_subjects, transform=training_transform)

patches_training_set = tio.Queue(
	subjects_dataset=training_set,
	max_length=300,
	samples_per_volume=1,
	sampler=tio.data.LabelSampler(patch_size, 'segmentation', label_probabilities={0: 0.3, 1: 0.6}),
	num_workers=num_workers,
	shuffle_subjects=True,
	shuffle_patches=True)

training_loader_patches = torch.utils.data.DataLoader(patches_training_set, batch_size=training_batch_size)

for batch_index, batch in enumerate(training_loader_patches):
	one_batch_flairs = batch['flair'][tio.DATA]
	print(one_batch_flairs)
```

### Actual outcome

I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f2861709e50>: attribute lookup <lambda> on __main__ failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f2861709e50>: attribute lookup <lambda> on __main__ failed

```

### Error messages

I get the following error:

```python-traceback

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f2861709e50>: attribute lookup <lambda> on __main__ failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f2861709e50>: attribute lookup <lambda> on __main__ failed

```

### Expected outcome

It should just print the flair tensor.

### System info

```shell
Platform:   Linux-4.15.0-135-generic-x86_64-with-glibc2.27
TorchIO:    0.18.86
PyTorch:    1.13.1+cu117
SimpleITK:  2.2.0 (ITK 5.3)
NumPy:      1.22.3
Python:     3.8.14 (default, Sep  8 2022, 00:02:10) 
[GCC 7.5.0]
```

**Comment by fepegar** [comment]
Hi, @arthursw. I can't reproduce on Colab using the following code:

```python
import torch
import torchio as tio
subject = tio.Subject(im=tio.ScalarImage(tensor=torch.rand(1, 2, 3, 4)))
transform = tio.ZNormalization(masking_method=lambda x: x > 0)
dataset = tio.SubjectsDataset([subject], transform=transform)
loader = torch.utils.data.DataLoader(dataset, num_workers=2)
next(iter(loader))
```

Can try defining the function instead of using a `lambda`?
