### ISSUE TITLE
tio.Resample does not work with custom image class

### ISSUE THREAD

**Issue by shahpnmlab** [fepegar/torchio#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

Hi,
I am working with MRC volumes (https://www.ccpem.ac.uk/mrc_format/mrc2014.php) for the purposes of training a standard 3DUNET. However, I am running into the below stated problem, when i am trying to resample the volumes onto a different grid. I am not sure where I am going wrong. So, would appreciate any pointers for correcting any glaring errors I may have made.

### Code for reproduction

```python
from pathlib import Path
import copy
import mrcfile
import numpy as np
import torchio as tio


# Define a function to read an mrc file
def read_mrc(path_to_data):
    with mrcfile.mmap(path_to_data) as m:
        data = m.data.copy()
        spacing = (m.voxel_size['x'], m.voxel_size['y'], m.voxel_size['z'])
        affine = np.diag(spacing + (1,))
    return data, affine

# Create a custom class to read MRC files that inherits from tio.Image
# and pass the read_mrc function to the reader arg.
class MRCImage(tio.Image):
    def __init__(self, path_to_data, type, **kwargs):
        super(MRCImage, self).__init__(path_to_data, type, reader=read_mrc, **kwargs)

    def __copy__(self):
        cls = self.__class__
        result = cls.__new__(cls)
        for k, v in self.__dict__.items():
            setattr(result, k, copy.copy(v))
        return result
tomogram_path = "test_data/volumes"
labels_path = "test_data/labels"
tomograms = sorted([f for ext in ('*.mrc', '*.rec') for f in Path(tomogram_path).glob(ext)])
labels = sorted([f for ext in ('*.mrc', '*.rec') for f in Path(labels_path).glob(ext)])

subjects = []
resampler = tio.Resample((30.0, 30., 30.))
for v, l in zip(tomograms, labels):

    subject = tio.Subject(
        tomogram=MRCImage(v, tio.INTENSITY),
        label=MRCImage(l, tio.LABEL)
    )

    subject = resampler(subject)
    subjects.append(subject)
```

### Actual outcome

Traceback (most recent call last):
  File "/Users/ps/data/wip/smol_AI/dataset.py", line 45, in <module>
    subject = resampler(subject)
  File "/Users/ps/software/mambaforge/envs/smol_AI/lib/python3.10/site-packages/torchio/transforms/transform.py", line 163, in __call__
    transformed = self.apply_transform(subject)
  File "/Users/ps/software/mambaforge/envs/smol_AI/lib/python3.10/site-packages/torchio/transforms/preprocessing/spatial/resample.py", line 189, in apply_transform
    floating_sitk = image.as_sitk(force_3d=True)
  File "/Users/ps/software/mambaforge/envs/smol_AI/lib/python3.10/site-packages/torchio/data/image.py", line 640, in as_sitk
    return nib_to_sitk(self.data, self.affine, **kwargs)
  File "/Users/ps/software/mambaforge/envs/smol_AI/lib/python3.10/site-packages/torchio/data/io.py", line 316, in nib_to_sitk
    origin, spacing, direction = get_sitk_metadata_from_ras_affine(
  File "/Users/ps/software/mambaforge/envs/smol_AI/lib/python3.10/site-packages/torchio/data/io.py", line 390, in get_sitk_metadata_from_ras_affine
    direction_ras, spacing_array = get_rotation_and_spacing_from_affine(affine)
  File "/Users/ps/software/mambaforge/envs/smol_AI/lib/python3.10/site-packages/torchio/data/io.py", line 285, in get_rotation_and_spacing_from_affine
    rotation = rotation_zoom / spacing
FloatingPointError: invalid value encountered in divide

### Expected outcome

I should have resampled volumes at the end of running tio.Resample.

### System info

```shell
Platform:   macOS-13.5.2-arm64-arm-64bit
TorchIO:    0.19.1
PyTorch:    2.0.0
SimpleITK:  2.2.1 (ITK 5.3)
NumPy:      1.25.2
Python:     3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
```

**Comment by fepegar** [comment]
Hi, @shahpnmlab. It seems that the spacing in your metadata is 0 for at least one dimension. Can you please try read an image with `image = sitk.ReadImage(path)` and print `image.GetSpacing()`?

**Comment by fepegar** [comment]
Closing due to inactivity. Feel free to reopen if necessary.
