### ISSUE TITLE
Inconsistent shapes for diffusion MRI

### ISSUE THREAD

**Issue by OeslleLucena** [fepegar/torchio#234]
Hi all, I am willing to use Torchio for diffusion MRI and this data is 4D. My plan is to use TorchIO for a patch-based regression where both the input and the output are diffusion MR images. To sample the patches, I am planning to use the intra-cranial mask as a sampling prior.

I ran the following code to try to apply a rotation transform to a subject and I have a `ValueError: Images in sample have inconsistent shapes`. I would appreciate any help with that issue. 

```
import torchio
from torchio.transforms import RandomAffine


image = '/xxx/aylj.nii.gz'
label = '/xxxx/aylj.nii.gz'
sample = '/xxxx/maskaylj.nii.gz'
subject = torchio.Subject(dMRI=torchio.Image(image, type=torchio.INTENSITY),
                          label=torchio.Image(image, type=torchio.INTENSITY),
                          sampling_map=torchio.Image(sample, type=torchio.SAMPLING_MAP))


transform = RandomAffine(degrees=(-10, 10),
                         isotropic=True)

transformed = transform(subject)

patch_size = 64
sampler = torchio.data.WeightedSampler(patch_size, probability_map='sampling_map')
sample = torchio.ImagesDataset([transformed])[0]
```

```
Traceback (most recent call last):
  File "test_torchio.py", line 17, in <module>
    transformed = transform(subject)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/transforms/augmentation/random_transform.py", line 33, in __call__
    return super().__call__(sample)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/transforms/transform.py", line 62, in __call__
    transformed = self.apply_transform(sample)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_affine.py", line 154, in apply_transform
    sample.check_consistent_shape()
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/subject.py", line 122, in check_consistent_shape
    raise ValueError(message)
ValueError: Images in sample have inconsistent shapes:
{'dMRI': (1, 128, 128, 69, 15),
 'label': (1, 128, 128, 69, 15),
 'sampling_map': (1, 128, 128, 69)}

```

Additionally, If I remove the sample from the Subject, the following error is raised:

```
Traceback (most recent call last):
  File "test_torchio.py", line 15, in <module>
    transformed = transform(subject)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/transforms/augmentation/random_transform.py", line 33, in __call__
    return super().__call__(sample)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/transforms/transform.py", line 62, in __call__
    transformed = self.apply_transform(sample)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_affine.py", line 184, in apply_transform
    center_lps=center,
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_affine.py", line 204, in apply_affine_transform
    assert tensor.ndim == 4
AssertionError
```

**Comment by fepegar** [comment]
Hi, @OeslleLucena. We don't have good support for 4D images yet (see e.g. #213), but I'll work on that soon.

For now, you could add each channel separately to the `Subject`.

**Comment by OeslleLucena** [comment]
Thank you @fepegar ! That would be very important for dMRI applications.

**Comment by fepegar** [comment]
I know it's not very convenient, but for now you could create a big dictionary with all your arrays:

```python
import numpy as np
import nibabel as nib
import torchio as tio

dmri_path = 'dmri.nii.gz'
label_path = 'label.nii.gz'
sampling_path = 'sampling.nii.gz'

nib.Nifti1Image(np.random.rand(128, 128, 69, 15), np.eye(4)).to_filename(dmri_path)
nib.Nifti1Image(np.random.rand(128, 128, 69, 15), np.eye(4)).to_filename(label_path)
nib.Nifti1Image(np.random.rand(128, 128, 69), np.eye(4)).to_filename(sampling_path)

def read(path):
    nii = nib.load(path)
    data = nii.get_fdata()
    if data.ndim == 4:
        data = data.transpose(3, 0, 1, 2)  # put channels first
    return data, nii.affine

dmri_data, dmri_affine = read(dmri_path)
label_data, label_affine = read(label_path)
sampling_data, sampling_affine = read(sampling_path)

big_dict = {}

for i, direction in enumerate(dmri_data):
    big_dict[f'dmri_{i}'] = tio.ScalarImage(tensor=direction, affine=dmri_affine)

for i, direction in enumerate(label_data):
    # I assume these are not discrete, but I guess you don't want intensity transformes for them
    big_dict[f'label_{i}'] = tio.LabelMap(tensor=direction, affine=label_affine)

big_dict['sampling'] = tio.Image(tensor=sampling_data, affine=sampling_affine, type=tio.SAMPLING_MAP)

subject = tio.Subject(big_dict)

transform = tio.RandomAffine()

transformed = transform(subject)
```

**Comment by OeslleLucena** [comment]
I guess that might work temporarily. I will see if I can write my scripts based on that workaround.
Thanks @fepegar

**Comment by fepegar** [comment]
This should work after #238. Feel free to reopen if it doesn't.

**Comment by OeslleLucena** [comment]
I still have inconsistent shapes error but now ont for the samples class.

```python
# Patch Sampling
sampler = torchio.data.WeightedSampler(patch_size, probability_map='sampling_map')
sample = torchio.ImagesDataset([transformed])[0]

for patch in sampler(sample):
    print(patch['index_ini'])

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-7b1ffccab345> in <module>
     50 sample = torchio.ImagesDataset([transformed])[0]
     51 
---> 52 for patch in sampler(sample):
     53     print(patch['index_ini'])
     54 

~/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/sampler/weighted.py in __call__(self, sample, num_patches)
     68             num_patches: Optional[int] = None,
     69             ) -> Generator[Subject, None, None]:
---> 70         sample.check_consistent_shape()
     71         if np.any(self.patch_size > sample.spatial_shape):
     72             message = (

~/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/subject.py in check_consistent_shape(self)
    118 
    119     def check_consistent_shape(self) -> None:
--> 120         self.check_consistent_attribute('shape')
    121 
    122     def check_consistent_spatial_shape(self) -> None:

~/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/subject.py in check_consistent_attribute(self, attribute)
    115                 f'\n{pprint.pformat(values_dict)}'
    116             )
--> 117             raise RuntimeError(message)
    118 
    119     def check_consistent_shape(self) -> None:

RuntimeError: More than one shape found in subject images:
{'dMRI': (15, 128, 128, 69),
 'label': (15, 128, 128, 69),
 'mask': (1, 128, 128, 69)}
```

**Comment by fepegar** [comment]
Makes sense. I think it line 70 of `torchio/data/sampler/weighted.py` should call `sample.check_consistent_spatial_shape()`. Would you mind opening a PR for that?

**Comment by OeslleLucena** [comment]
@fepegar sure! I would do that :)
