### ISSUE TITLE
DataLoader worker (pid 38351) is killed by signal: Killed

### ISSUE THREAD

**Issue by wendy-xiaozong** [fepegar/torchio#255]
Hi all, 
Thanks a lot for this great tool! 

I am using the `Patch-based pipelines`. I keep running into this error and I have tried to reduce `max_queue_length` in the `torchio.data.Queue`.But it cannot solve it. I think memory should be fine for the number of subjects I have chosen.  It happened after the model has run for a long time ( usually more than ten hours). 

Any ideas about it?

Thanks!
```python-traceback
Filling queue from 50 subjects...
 20%|██        | 10/50 [01:00<05:20,  8.01s/it]Traceback (most recent call last):
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torchio/data/queue.py", line 106, in __getitem__
    self.fill()
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torchio/data/queue.py", line 163, in fill
    patches = list(islice(iterable, self.samples_per_volume))
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torchio/data/sampler/weighted.py", line 84, in __call__
    yield self.extract_patch(sample, probability_map, cdf, sort_indices)
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torchio/data/sampler/weighted.py", line 201, in extract_patch
    index_ini = self.get_random_index_ini(probability_map, cdf, sort_indices)
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torchio/data/sampler/weighted.py", line 213, in get_random_index_ini
    center = self.sample_probability_map(probability_map, cdf, sort_indices)
  File "/home/jueqi/ENV/lib/python3.6/site-packages/torchio/data/sampler/weighted.py", line 247, in sample_probability_map
    if random_number > cdf.max():
  File "/home/jueqi/ENV/lib/python3.6/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
```

**Comment by fepegar** [comment]
Hi, @wendy-xiaozong.

> It happened after the model has run for a long time ( usually more than ten hours).

That's a bummer. It looks like a PyTorch problem. Have you searched that error in their issues? Also, can you post the actual message too and not just the traceback?

**Comment by wendy-xiaozong** [comment]
Hi @fepegar,
Thanks for your quick response and reminding me. I am searching this error in PyTorch issue right now. 

Does the actual message mean the last line of the traceback? If it is, the message is:
```
RuntimeError: DataLoader worker (pid 38351) is killed by signal: Killed. 
```

**Comment by fepegar** [comment]
I think I've solved that issue on my macOS by using `num_workers=0` for the `DataLoader`, but it didn't train for 10 hours...

Anyway, here are some issues that might be related:
- https://github.com/pytorch/pytorch/issues/8976
- https://github.com/pytorch/pytorch/issues/4507
- https://github.com/pytorch/pytorch/issues/7943

**Comment by wendy-xiaozong** [comment]
Hi @fepegar , thanks for those links

I think I might have solved this problem by continuing to reduce the `max_queue_length` or set the `num_worker=0`. I recommend reducing the `max_queue_length` more since it runs faster in my machine (like it takes 10h when I set the original number of `num_worker`, it would take 11h when I set `num_worker=0` for the same amount of work).

**Comment by fepegar** [comment]
Glad you solved it. Out of curiosity, what queue length and patch size were you using?

**Comment by wendy-xiaozong** [comment]
I am using `max_queue_length=500` and `patch_size=96`

**Comment by fepegar** [comment]
I see. FYI if you have `N` images per patch, your queue can store `500 samples x 96**3 voxels/patch x 4 Bytes/voxel x N patches/sample / 2**30 = N * 1.65 GiB`, which is quite a lot. If your computer is not very powerful, you might want to be careful with that queue length.
