### ISSUE TITLE
RuntimeError: DataLoader worker (pid 38357) is killed by signal: Bus error

### ISSUE THREAD

**Issue by OeslleLucena** [fepegar/torchio#295]
I am training m CNN with 67 subject images (4D dMRI) and I am using the folowing parameters for a patch-based training:

```python
    patch_overlap = 8
    patch_size = 16
    seed = 42  # for reproducibility
    num_epochs = 1
    batch_size = 40
    samples_per_volume = 40
    max_queue_length = 5*batch_size
    scales = (0.9, 1.2)
    degrees = (-20, 20)
    isotropic = True
    num_workers = 0
    num_input_channels = 15
    num_output_channels = 73
```

When I run a quick example with the following parameters for a subset containing 14 subjects for training I have a successful training:

```
[INFO] GPU available.
[INFO] Epoch 1/1 lr 0.03
100%|██████████| 14/14 [02:20<00:00, 10.05s/it]
Training complete in 2m 21s
```

Nonetheless, when I try to use all the 67 subject images to train my CNN I end up with a `RuntimeError: DataLoader worker`. 
See below the full error.

```python-traceback
[INFO] GPU available.
[INFO] Epoch 1/1 lr 0.03
  0%|          | 0/67 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
 ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
  0%|          | 0/67 [01:11<?, ?it/s]
Traceback (most recent call last):
  File "/home/ol18/Codes/TractUncertainty/segmentation_sh_torchIO.py", line 445, in <module>
    checkpoint_path, tensorboadx_path)
  File "/home/ol18/Codes/TractUncertainty/segmentation_sh_torchIO.py", line 97, in __init__
    checkpoint_path)
  File "/home/ol18/Codes/TractUncertainty/segmentation_sh_torchIO.py", line 263, in run_training
    running_loss = self.run_one_epoch(model, TRAINING)
  File "/home/ol18/Codes/TractUncertainty/segmentation_sh_torchIO.py", line 226, in run_one_epoch
    for minibatch in iterable:
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/queue.py", line 106, in __getitem__
    self.fill()
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/queue.py", line 163, in fill
    patches = list(islice(iterable, self.samples_per_volume))
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 38357) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

```

Is there anything related to `torchio.Queue()` that I am not aware that messes up with PyTorch dataloader?
I have changed the `num_wokers` in the dataloader like recommended in https://github.com/fepegar/torchio/issues/255#issue-674414031 and it did not solve the problem.
Below you can find the way I am invoking torchIO queue.

```python
    def get_patch_based_datasets(self, subjects_list, transform,
                                 max_queue_length, patch_size, samples_per_volume):
        # Datasets
        training_set = torchio.data.SubjectsDataset(subjects_list[TRAINING],
                                                    transform=transform)

        validation_set = torchio.data.SubjectsDataset(subjects_list[VALIDATION])

        patch_datasets = {
            x: torchio.Queue(
                subjects_dataset=y,
                max_length=max_queue_length,
                samples_per_volume=samples_per_volume,
                sampler=torchio.sampler.WeightedSampler(patch_size,
                                                        probability_map='sampling_map'),
                num_workers=4, 
                shuffle_subjects=True,
                shuffle_patches=True
            )
            for x, y in zip([TRAINING, VALIDATION], [training_set, validation_set])
        }
        return patch_datasets
```

**Comment by fepegar** [comment]
It looks like you're trying to use too much memory. What's the shape of each image in each instance of `Subject`?

Are you using Docker?

Related issues: https://github.com/pytorch/pytorch/issues/5040, https://github.com/pytorch/pytorch/issues/8976#issuecomment-481442240

**Comment by OeslleLucena** [comment]
I am not using a docker. Each `Subject` instance has three images: dMRI (145 x 174 x 145 x 1 x 15), label (binary mask) (145 x 174 x 145 x 1 x 73) and sampling map (145 x 174 x 145 x 1). The dMRI is 65MB, The label is 2.1 MB and the sampling map is 140 kB.

The issue occurs when I increase the number of subject images. I reduced the max_queue_length but did not work.

**Comment by OeslleLucena** [comment]
manage to make it work by  setting `num_workers=2` in the Queue and `num_workers=0` in the Dataloader.
