### ISSUE TITLE
Dataloader for patch based inference 

### ISSUE THREAD

**Issue by OeslleLucena** [fepegar/torchio#298]
Hi guys, I am trying to use `collate_fn` as described in here [link](https://www.gitmemory.com/issue/fepegar/torchio/256/670878239 to have a data loader for subject samples in order to have a code compatible for `test_loader` from pytorch lightning. 

Here is a snippet from what I have to run the inference.
``` python
    self.inference_set = torchio.data.SubjectsDataset(subjects_list[INFERENCE])

    def test_dataloader(self):
        test_loader = DataLoader(self.inference_set,
                                  batch_size=1,
                                  collate_fn=lambda x:x,
                                  num_workers=0)
        return test_loader

    def test_step(self, batch, batch_idx):
        print(batch)

logger = TensorBoardLogger('tbs', name='tb_test')
model = LitUnet(num_input_channels=num_input_channels,
                num_output_channels=num_output_channels,
                activation=activation)
trainer = Trainer(max_epochs=num_epochs,
                  gpus=1,
                  logger=logger,
                  row_log_interval=1,
                  check_val_every_n_epoch=validation_every_n_epochs)
trainer.test(model)
```

After running this script, I have the following error from torchIO:

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: Could not log computational graph since the `model.example_input_array` attribute is not set or `input_array` was not given
  warnings.warn(*args, **kwargs)
/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:37: UserWarning: The dataloader, test dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Testing: 0it [00:00, ?it/s]/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/image.py:110: UserWarning: Not specifying the image type is deprecated and will be mandatory in the future. You can probably use ScalarImage or LabelMap instead
  'Not specifying the image type is deprecated and will be'
Traceback (most recent call last):
  File "/home/ol18/Codes/TractUncertainty/segmentation_sh_torchIO_pytorch_lightning.py", line 267, in <module>
    trainer.test(model)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1355, in test
    results = self.__test_given_model(model, test_dataloaders)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1418, in __test_given_model
    results = self.fit(model)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1073, in fit
    results = self.accelerator_backend.train(model)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 51, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1209, in run_pretrain_routine
    eval_loop_results, _ = self.run_evaluation(test_mode=True)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 582, in run_evaluation
    eval_results = self._evaluate(self.model, dataloaders, max_batches, test_mode)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 333, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 675, in evaluation_forward
    batch = self.transfer_batch_to_gpu(batch, root_gpu)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 174, in transfer_batch_to_gpu
    return self.__transfer_batch_to_device(batch, device)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 179, in __transfer_batch_to_device
    return model.transfer_batch_to_device(batch, device)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/core/hooks.py", line 382, in transfer_batch_to_device
    return move_data_to_device(batch, device)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 124, in move_data_to_device
    return apply_to_collection(batch, dtype=(TransferableDataType, Batch), function=batch_to)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 58, in apply_to_collection
    return elem_type([apply_to_collection(d, dtype, function, *args, **kwargs) for d in data])
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 58, in <listcomp>
    return elem_type([apply_to_collection(d, dtype, function, *args, **kwargs) for d in data])
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 54, in apply_to_collection
    for k, v in data.items()})
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 54, in <dictcomp>
    for k, v in data.items()})
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 54, in apply_to_collection
    for k, v in data.items()})
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/image.py", line 132, in _init_
    self.path = self._parse_path(path)
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/image.py", line 324, in _parse_path
    return [self._parse_single_path(p) for p in path]
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/image.py", line 324, in <listcomp>
    return [self._parse_single_path(p) for p in path]
  File "/home/ol18/miniconda3/envs/tract_uncertainty/lib/python3.6/site-packages/torchio/data/image.py", line 312, in _parse_single_path
    raise FileNotFoundError(f'File not found: {path}')
FileNotFoundError: File not found: path
````

Any ideas on why is that happening?

**Comment by fepegar** [comment]
Hi @OeslleLucena!

> Hi guys, I am trying to use collate_fn as described in here [link](https://www.gitmemory.com/issue/fepegar/torchio/256/670878239 

I suggest you look at the issues on GitHub and not gitmemory, as there might be new replies that could be helpful for you.

> Any ideas on why is that happening?

Most of the traceback has been written by PT Lightning, but it looks like an instance of `Image` has received a value of `'path'` for the image path.

**Comment by fepegar** [comment]
Have you solved this?

**Comment by OeslleLucena** [comment]
yep!

this is how I fixed it:

```python
        test_loader = DataLoader([self.inference_set],
                                  batch_size=1,
                                  collate_fn=lambda x:x,
                                  num_workers=0,
                                 pin_memory=True
                                 )
```

**Comment by fepegar** [comment]
I'm not sure what the problem was and why it was solved, but I'm glad it's working now.
