### ISSUE TITLE
Development environment can't be installed on Windows

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#350]
**🐛Bug**

Reported by @sarthakpati in #347.

**To reproduce**

```bash
git@github.com:fepegar/torchio.git
pip install --editable ./torchio
```

```python-traceback
(C:\Projects\torchio\venv) PS C:\Projects\torchio> pip install --editable .
Obtaining file:///C:/Projects/torchio
    ERROR: Command errored out with exit status 1:
     command: 'C:\Projects\torchio\venv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Projects\\torchio\\setup.py'"'"'; __file__='"'"'C:\\Projects\\torchio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sarth\AppData\Local\Temp\pip-pip-egg-info-o9yqppbr'
         cwd: C:\Projects\torchio\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Projects\torchio\setup.py", line 8, in <module>
        readme = readme_file.read()
      File "C:\Projects\torchio\venv\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 14173: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sarthakpati** [comment]
Was there something wrong I was doing?

**Comment by fepegar** [comment]
No! I think it was just an encoding issue: https://stackoverflow.com/questions/49640513/unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d-in-position-x-charac

It'd be great if you could try again, as I don't have access to a Windows computer ATM.

**Comment by sarthakpati** [comment]
> No! I think it was just an encoding issue: https://stackoverflow.com/questions/49640513/unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d-in-position-x-charac

But, where?

**Comment by fepegar** [comment]
I think the README file wasn't being read correctly in `setup.py`, which `pip` uses to install the library: 9f4f7b4
