### ISSUE TITLE
Unable to run GridSampler

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#357]
Hi,

I am running into a weird error while running the GridSampler:

```python-traceback
Traceback (most recent call last):
  File "/cbica/projects/code/venv_92/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cbica/projects/code/venv_92/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gpfs/fs001/cbica/projects/code/training_loop.py", line 382, in <module>
    holdoutDataFromPickle=holdoutDataFromPickle,)
  File "/gpfs/fs001/cbica/projects/code/training_loop.py", line 292, in trainingLoop
    average_val_dice, average_val_loss = get_metrics_save_mask(model, val_loader, psize, channel_keys, class_list, loss_fn)
  File "/gpfs/fs001/cbica/projects/code/utils.py", line 126, in get_metrics_save_mask
    grid_sampler = torchio.inference.GridSampler(subject , psize)
  File "/cbica/projects/code/venv_92/lib/python3.6/site-packages/torchio/data/inference/grid_sampler.py", line 60, in __init__
    sizes = self.subject.spatial_shape, self.patch_size, self.patch_overlap
AttributeError: 'dict' object has no attribute 'spatial_shape'
```

My subject dictionary contains 2 entries: 'image' and 'label'. I didn't realize that I needed to have 'spatial_shape' there, too?

Cheers,
Sarthak

**Comment by fepegar** [comment]
The docs for grid sampler explicitly say the `subject` argument must be an instance of `torchio.Subject`. Is it?

**Comment by sarthakpati** [comment]
> The docs for grid sampler explicitly say the `subject` argument must be an instance of `torchio.Subject`. Is it?

Yup, here's my code:
```python
for batch_idx, (subject) in enumerate(loader):
    grid_sampler = torchio.inference.GridSampler(subject , patch_size)
```

`loader` is a [torch.DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) type.

**Comment by fepegar** [comment]
In that snippet, `subject` is a `dict`, not a `tio.Subject`. Take a look at the example in the [Inference section of the docs](https://torchio.readthedocs.io/data/patch_inference.html?highlight=gridsample#inference).

**Comment by sarthakpati** [comment]
You are right, thanks.
