### ISSUE TITLE
RandomElasticDeformation wrong type after updating to 0.18.27

### ISSUE THREAD

**Issue by Linardos** [fepegar/torchio#460]
**🐛Bug**

After updating to version 0.18.27 it seems something changed with RandomElasticDeformation and it gives me an error. 
RuntimeError: Expected object of scalar type Double but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'
I thing the problem is clear, somehow this transformation now changes the type of the input to Float. I am reverting to 0.18.0 and it works fine.

**Comment by fepegar** [comment]
Can you please provide the error message, and code to reproduce, as it's asked in the issue template?

**Comment by Linardos** [comment]
Sorry for the rushed message, I am pressed for time these days with the MICCAI deadline approaching but I thought I should at least report it. I had a hard time reproducing it. I run the following in both versions (0.18.0 and 0.18.28): 
```

import torchio as tio                                                                                                                                                                                                                                         

colin = tio.datasets.Colin27()                                                                                                                                                                                                                                

transformed = tio.RandomElasticDeformation(num_control_points=5, max_displacement=2)(colin)                                                                                                                                                                                                                     

transformed.t1.data.dtype
```
But I get torch.float32 so that's not the problem. 
However the issue in the newest version does seem related to a data type and it only disappears when I get rid of the ElasticDeformation. When I move back to the old version I can use the transformation just fine. The error I'm getting in detail is the following:

```
Traceback (most recent call last):
  File "train.py", line 520, in <module>
    fold=fold)
  File "train.py", line 166, in train
    model, opt, epoch_losses, epoch_accuracies, _ = run_epoch(training_loader, model, opt, criterion, device, epoch=epoch, is_training = True)
  File "train.py", line 312, in run_epoch
    for i, batch in enumerate(tqdm(loader)):
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/linardos/anaconda3/envs/breast/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: Expected object of scalar type Double but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'
```

I tried adding some more of the transformations I'm using in case the interplay is the problem, but it seems it somehow correlates to the data loader so making a reproducible example is going to be a bit more complex. Let me know if any of this rings a bell, otherwise I'll try to figure out how to make a reproducible example after the MICCAI deadline. I'm using the old version for now.

**Comment by fepegar** [comment]
Thanks for the more detailed report. What version of PyTorch are you using?

**Comment by Linardos** [comment]
1.4.0

**Comment by fepegar** [comment]
I can reproduce on 1.4 but not on 1.7.1. Please upgrade PyTorch. Good luck for MICCAI!

**Comment by Linardos** [comment]
Just curious, could you share how you reproduced it? And thanks!

**Comment by fepegar** [comment]
No worries! Here it is:

```python
In [1]: import torch
   ...: import torchio as tio

In [2]: t1 = torch.rand(1, 3, 3, 3).byte()

In [3]: t2 = torch.rand(1, 3, 3, 3)

In [4]: s1 = tio.Subject(im=tio.ScalarImage(tensor=t1))
   ...: s2 = tio.Subject(im=tio.ScalarImage(tensor=t2))

In [5]: dataset = tio.SubjectsDataset((s1, s2))

In [6]: loader = torch.utils.data.DataLoader(dataset, batch_size=2)
   ...: iter(loader).next()
```

```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-2386a34d7498> in <module>
      1 loader = torch.utils.data.DataLoader(dataset, batch_size=2)
----> 2 iter(loader).next()

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    383     def _next_data(self):
    384         index = self._next_index()  # may raise StopIteration
--> 385         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    386         if self._pin_memory:
    387             data = _utils.pin_memory.pin_memory(data)

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     45         else:
     46             data = self.dataset[possibly_batched_index]
---> 47         return self.collate_fn(data)

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in <dictcomp>(.0)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in <dictcomp>(.0)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

~/miniconda3/envs/test/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     53             storage = elem.storage()._new_shared(numel)
     54             out = elem.new(storage)
---> 55         return torch.stack(batch, 0, out=out)
     56     elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
     57             and elem_type.__name__ != 'string_':

RuntimeError: Expected object of scalar type Byte but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'
```
