### ISSUE TITLE
When I tried to use the training example of Patch-based pipelines in the help document, the following error occurred

### ISSUE THREAD

**Issue by Key-lei** [fepegar/torchio#474]
**🐛Bug**

**To reproduce**

```python
import torch
import torchio as tio
from torch.utils.data import DataLoader

patch_size = 96
queue_length = 300
samples_per_volume = 10
sampler = tio.data.UniformSampler(patch_size)
subject = tio.datasets.Colin27()
subjects_dataset = tio.SubjectsDataset(10 * [subject])
patches_queue = tio.Queue(
    subjects_dataset,
    queue_length,
    samples_per_volume,
    sampler,
    num_workers=0,
)
patches_loader = DataLoader(patches_queue, batch_size=16)
num_epochs = 2
model = torch.nn.Identity()
for epoch_index in range(num_epochs):
    for patches_batch in patches_loader:
        inputs = patches_batch['t1'][tio.DATA]  # key 't1' is in subject
        targets = patches_batch['brain'][tio.DATA]  # key 'brain' is in subject
        logits = model(inputs)  # model being an instance of torch.nn.Module
```

**Expected behavior**
```
It should be an iterable object
```

**Actual behavior**

```python-traceback
TypeError: randint(): argument 'high' (position 1) must be int, not numpy.int32
```

**System info**

Output of

```
TypeError: randint(): argument 'high' (position 1) must be int, not numpy.int32
```

**Comment by fepegar** [comment]
Hi, @Key-lei. Can you please post the full error message? Are you running the notebook locally? Can you run `python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)` and share the output?

**Comment by Key-lei** [comment]
I am running the notebook locally, the following is my complete error report
```python
Traceback (most recent call last):
  File "D:/Mac/GitHubDeepLearing/Lung_data/test.py", line 28, in <module>
    for patches_batch in patches_loader:
  File "D:\anaconda3\envs\GitHubDeepLearing\lib\site-packages\torch\utils\data\dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda3\envs\GitHubDeepLearing\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\GitHubDeepLearing\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\GitHubDeepLearing\lib\site-packages\torchio\data\queue.py", line 164, in __getitem__
    self.fill()
  File "D:\anaconda3\envs\GitHubDeepLearing\lib\site-packages\torchio\data\queue.py", line 230, in fill
    patches = list(islice(iterable, self.samples_per_volume))
  File "D:\anaconda3\envs\GitHubDeepLearing\lib\site-packages\torchio\data\sampler\uniform.py", line 40, in __call__
    for x in valid_range
  File "D:\anaconda3\envs\GitHubDeepLearing\lib\site-packages\torchio\data\sampler\uniform.py", line 40, in <listcomp>
    for x in valid_range
TypeError: randint(): argument 'high' (position 1) must be int, not numpy.int32

Process finished with exit code 1

```

> 嗨，@ Key-lei。您能否发布完整的错误消息？您在本地运行笔记本吗？您可以运行`python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)`并共享输出吗？
> 
> 嗨@ key-lei。你能发布完整的错误信息吗？你在本地运行笔记本吗？你能运行python <（curl-s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py ）并共享输出吗？

**Comment by fepegar** [comment]
Ok, thanks. I guess that system config command doesn't work on Windows. What version of PyTorch are you using? Could you please upgrade and try again?

**Comment by rayryeng** [comment]
This occurs because you have an older version of Numpy. Please update to the latest version.

**Comment by fepegar** [comment]
> This occurs because you have an older version of Numpy. Please update to the latest version. Also make sure you update PyTorch to at least version 1.6.0

Thanks, @rayryeng. @Key-lei, feel free to reopen if that solution does not help.
