### ISSUE TITLE
'Tensor' object has no attribute 'astype'

### ISSUE THREAD

**Issue by diazandr3s** [fepegar/torchio#475]
**🐛Bug**

Hi, 

I'm trying to use the TorchIO module in 3D Slicer and I couldn't make work. I always got the following error:

![errorTorchIO](https://user-images.githubusercontent.com/11991079/109370649-1609c300-7899-11eb-91fe-fe41fee76aef.png)

**To reproduce**

```
I got the error when trying to use all the transforms available in 3D Slicer for versions Slicer-4.11 and Slicer-4.13.0
```

**Expected behavior**

I expect the transforms to work in 3D Slicer module

**Actual behavior**

```python-traceback

TorchIO version: 0.18.29
Transform args: {'num_spikes': 1, 'intensity': 2.0}
TorchIO returned the error: Traceback (most recent call last):
  File "/home/adp20local/Documents/viewers/Slicer-4.13.0-2021-02-04-linux-amd64/NA-MIC/Extensions-29688/TorchIO/lib/Slicer-4.13/qt-scripted-modules/TorchIOTransforms.py", line 201, in onApplyButton
    outputImage = self.currentTransform(inputVolumeNode, outputVolumeNode)
  File "/home/adp20local/Documents/viewers/Slicer-4.13.0-2021-02-04-linux-amd64/NA-MIC/Extensions-29688/TorchIO/lib/Slicer-4.13/qt-scripted-modules/TorchIOTransformsLib/Transform.py", line 119, in __call__
    tensor = torch.from_numpy(data.astype(np.float32))  # why do I need this? Open a TorchIO issue?
AttributeError: 'Tensor' object has no attribute 'astype'
```

**System info**

Output of `python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)`:

```
Not sure this is useful as this info comes from a virtual env.

Platform: Linux-5.4.0-66-generic-x86_64-with-debian-bullseye-sid
TorchIO:  0.18.29
PyTorch:  1.7.1
NumPy:    1.19.5
Python:   3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0]
```

**Comment by fepegar** [comment]
Thanks, @diazandr3s! It should be fixed in tomorrow's preview version.

**Comment by diazandr3s** [comment]
Superb, thanks!

**Comment by fepegar** [comment]
@all-contributors please add @diazandr3s for bug
