### ISSUE TITLE
Encounter "TypeError: only integer scalar arrays can be converted to a scalar index" when using random flip

### ISSUE THREAD

**Issue by hsiangyuzhao** [fepegar/torchio#529]
**🐛Bug**

**To reproduce**

```python
augment = tio.Compose([
            tio.RandomFlip(p=0.5),
            #tio.RandomAffine(),
            #tio.RandomGamma(p=0.5),
            #tio.RandomNoise(p=0.5)
])
trainset = tio.SubjectsDataset(subjects=train_subjects, transform=tio.Compose([augment, preprocess]))
train_queue = tio.Queue(subjects_dataset=trainset,
                            max_length=max_length,
                            sampler=sampler,
                            samples_per_volume=samples_per_volume,
                            num_workers=0,
                            shuffle_patches=False,
                            shuffle_subjects=False)
train_loader = DataLoader(train_queue, batch_size=batch_size, num_workers=0, pin_memory=False)
for step, batch_data in enumerate(loader):
    ...
```

**Expected behavior**

Training patches shall be augmented.

**Actual behavior**

```python-traceback
Traceback (most recent call last):
  File "<input>", line 85, in <module>
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 165, in __getitem__
    self._fill()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 229, in _fill
    subject = self._get_next_subject()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 239, in _get_next_subject
    subject = next(self.subjects_iterable)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/dataset.py", line 85, in __getitem__
    subject = self._transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/composition.py", line 47, in apply_transform
    subject = transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/composition.py", line 47, in apply_transform
    subject = transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 60, in apply_transform
    transformed = transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 91, in apply_transform
    _flip_image(image, axes)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 128, in _flip_image
    data = np.flip(data, axis=spatial_axes)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/numpy/lib/function_base.py", line 206, in flip
    indexer[axis] = slice(None, None, -1)
TypeError: only integer scalar arrays can be converted to a scalar index
```

**System info**

When I cancel random flip augmentation, the code would work fine.
I suppose this is because of the version of numpy. For latest numpy the error would occur, but for numpy version 1.19.1 the error won't happen. 
System ubuntu 16.04, torchio version 0.18.37, python 3.6, pytorch 1.7.1, numpy 1.19.5.

**Comment by fepegar** [comment]
Hi, @hsiangyuzhao. Thanks for reporting. I haven't been able to reproduce this, but I'll commit a fix that will hopefully make the implementation compatible with older versions.

**Comment by fepegar** [comment]
@all-contributors please add @hsiangyuzhao for bug.

**Comment by hsiangyuzhao** [comment]
Hello @fepegar , thanks for your effort. I have modified my code as you did, but new errors occur.
```python
Traceback (most recent call last):
  File "train.py", line 95, in <module>
    for step, batch_data in enumerate(loader):
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 165, in __getitem__
    self._fill()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 229, in _fill
    subject = self._get_next_subject()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 239, in _get_next_subject
    subject = next(self.subjects_iterable)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/dataset.py", line 85, in __getitem__
    subject = self._transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/composition.py", line 47, in apply_transform
    subject = transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/composition.py", line 47, in apply_transform
    subject = transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 60, in apply_transform
    transformed = transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 91, in apply_transform
    _flip_image(image, axes)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 128, in _flip_image
    data = np.flip(data, axis=spatial_axes.tolist())
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/numpy/lib/function_base.py", line 206, in flip
    indexer[axis] = slice(None, None, -1)
TypeError: list indices must be integers or slices, not list
```
Will you look into it at your convenience? Thanks!

**Comment by fepegar** [comment]
Could you please provide a minimal working example to reproduce this and confirm your version of NumPy?

Does this work on your computer?

```shell
python -c "import numpy as np; print(np.__version__); import torchio as tio; tio.Flip((0, 1))(tio.datasets.Colin27())"
```

**Comment by hsiangyuzhao** [comment]
Hi @fepegar , I double checked my numpy version and I found that 2 versions of numpy (1.13.1 and 1.19.5) exist in my conda virtual env (I don't know why). When I use 'conda list' command I see the version is 1.19.5, but actually when using in python version 1.13.1 is the one that works. So the error listed in https://github.com/fepegar/torchio/issues/529#issue-887668967 actually happens with numpy 1.13.1:
```python
(torch) zhao@zhao-Z390-GAMING-X:~/Projects/BrainSeg_MONAI$ python -c "import numpy as np; print(np.__version__); import torchio as tio; tio.Flip((0, 1))(tio.datasets.Colin27())"
1.13.1
Downloading http://packages.bic.mni.mcgill.ca/mni-models/colin27/mni_colin27_1998_nifti.zip to /home/zhao/.cache/torchio/mni_colin27_1998_nifti/mni_colin27_1998_nifti.zip
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 23871488/24250681 [00:14<00:00, 2932403.73it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/transform.py", line 121, in __call__
    transformed = self.apply_transform(subject)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 91, in apply_transform
    _flip_image(image, axes)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/transforms/augmentation/spatial/random_flip.py", line 128, in _flip_image
    data = np.flip(data, axis=spatial_axes)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/numpy/lib/function_base.py", line 206, in flip
    indexer[axis] = slice(None, None, -1)
TypeError: only integer scalar arrays can be converted to a scalar index
24256512it [00:14, 1664705.74it/s]                                     
```
Then I reinstalled my numpy. For numpy 1.19.1 and 1.19.5 it works fine:
```python
(torch) zhao@zhao-Z390-GAMING-X:~/Projects/BrainSeg_MONAI$ python -c "import numpy as np; print(np.__version__); import torchio as tio; tio.Flip((0, 1))(tio.datasets.Colin27())"
1.19.5
```
```python
(torch) F:\Projects\Python\BrainSeg_MONAI>python -c "import numpy as np; print(np.__version__); import torchio as tio; tio.Flip((0, 1))(tio.datasets.Colin27())"
1.19.1
```

So I think both the errors happen in https://github.com/fepegar/torchio/issues/529#issue-887668967 and https://github.com/fepegar/torchio/issues/529#issuecomment-839373343 are actually caused by the older versions of numpy, rather than the latest ones. 
Sorry for the trouble I have caused, I deeply appreciate your patience and efforts, and thank you for providing such an excellent package for medical imaging. But still Commit e6f8e9c does not solve the inconsistency of torchio and older versions of numpy (Actually latest numpy works fine with or without Commit e6f8e9c), will you look into it in the future or update the readme page to remind users to update their numpy?

**Comment by fepegar** [comment]
Thanks for looking into it.

NumPy 1.13.1 is from July 2017, so I think it's fair not to support it. I haven't even been able to install it alongside TorchIO.
1.15, where the functionality of `np.flip` was changed, is from July 2018. I am going to add `1.15` as the minimum version for NumPy in the requirements.
