### ISSUE TITLE
worker error after some training epoch with patch based training

### ISSUE THREAD

**Issue by Chop1** [fepegar/torchio#559]
**🐛Bug**
When training a CNN using a patch sampler, a runtime error related to a worker is rised.

**To reproduce**

here is my dataloader

```python
from pathlib import Path
import torch
import torchio as tio
import numpy as np
from torch.utils.data import DataLoader, random_split
import pytorch_lightning as pl
import re
import math

class KitsDataModule(pl.LightningDataModule):

    def __init__(self, dataset_path: Path,
                 patch_size: int = 64,
                 queue_length: int = 16,
                 samples_per_volume: int = 4,
                 batch_size: int = 1,
                 train_val_ratio: float = 0.7):

        super().__init__()
        
        def sorted_nicely(list_to_sort: list):
            convert = lambda text: int(text) if text.isdigit() else text
            alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
            return sorted(list_to_sort, key=alphanum_key)
        
        self.patch_size = patch_size
        self.queue_length = queue_length
        self.samples_per_volume = samples_per_volume
        self.batch_size = batch_size
        self.train_val_ratio = train_val_ratio
        
        #self.sampler = tio.data.UniformSampler(self.patch_size)
        probabilities = {0: 0.1,
                         1: 0.1,
                         2: 0.1,
                         3: 0.1,
                         4: 0.1,
                         5: 0.1,
                         6: 0.1}
        
        self.sampler = tio.data.LabelSampler(
            patch_size=self.patch_size,
            label_name='label',
            label_probabilities=probabilities,
        )
        
        # get paths of ct images
        self.path_imgs = [str(x) for x in dataset_path.glob("**/imaging.nii.gz")]
        self.path_imgs = sorted_nicely(self.path_imgs)
        
        # get paths of corresponding labels images
        self.path_masks = [str(x) for x in dataset_path.glob("**/aggregated_OR_seg.nii.gz")]
        self.path_masks = sorted_nicely(self.path_masks)
        
        # since not all labels are available, we only keep the available pairs of (imgs, masks)
        n_available = len(self.path_masks)
        self.path_imgs = self.path_imgs[:n_available]
        
    def get_max_shape(self, subjects):
        dataset = tio.SubjectsDataset(subjects)
        shapes = np.array([s.spatial_shape for s in dataset])
        return shapes.max(axis=0)
        
    def get_preprocessing_transform(self):
        ct_min, ct_max = -200, 500
        preprocess = tio.Compose([
            tio.Resample(0.9, image_interpolation='bspline'),  # resample all images to 1mm iso
            tio.RescaleIntensity(out_min_max=(-1, 1),
                                 in_min_max=(ct_min, ct_max),
                                 percentiles=(0.5, 99.5)),
            tio.ZNormalization(),
            #tio.CropOrPad(self.get_max_shape(self.subjects)),
            #tio.EnsureShapeMultiple(8),  # for the U-Net
            tio.OneHot(num_classes=7),
        ])
        return preprocess
        
    def get_augmentation_transform(self):
        augment = tio.Compose([
            tio.OneOf({
                tio.RandomAffine(): 0.6,
                tio.RandomElasticDeformation(max_displacement=12, num_control_points=(7, 7, 7), locked_borders=2): 0.4,
            }, p=0.75),
            tio.RandomMotion(p=0.1),
            tio.RandomGamma(p=0.1),
            tio.RandomNoise(p=0.1),
        ])
        return augment
        
    def setup(self, stage=None):
        
        self.subjects = []
        for image_path, label_path in zip(self.path_imgs, self.path_masks):
            subject = tio.Subject(
                image=tio.ScalarImage(image_path),
                label=tio.LabelMap(label_path)
            )
            self.subjects.append(subject)
            
        self.preprocess = self.get_preprocessing_transform()
        augment = self.get_augmentation_transform()
        self.transform = tio.Compose([self.preprocess, augment])
            
        num_subjects = len(self.subjects)
        num_train_subjects = int(round(num_subjects * self.train_val_ratio))
        num_val_subjects = num_subjects - num_train_subjects
        splits = num_train_subjects, num_val_subjects
        train_subjects, val_subjects = random_split(self.subjects, splits, generator=torch.Generator().manual_seed(42))
        
        self.train_set = tio.SubjectsDataset(train_subjects, transform=self.transform)
        self.val_set = tio.SubjectsDataset(val_subjects, transform=self.preprocess)
        
    def train_dataloader(self):
        
        patches_queue = tio.Queue(
            self.train_set,
            self.queue_length,
            self.samples_per_volume,
            self.sampler,
            num_workers=1,
        )
        return DataLoader(patches_queue, self.batch_size)

    def val_dataloader(self):
        
        patches_queue = tio.Queue(
            self.val_set,
            self.queue_length,
            self.samples_per_volume,
            self.sampler,
            num_workers=1,
        )
        return DataLoader(patches_queue, 1)
```

my model:
```python
class Block(nn.Module):
    def __init__(self, in_ch, out_ch, kernel_size=3):
        super().__init__()
        self.conv1 = nn.Conv3d(in_ch, out_ch, kernel_size, padding=1)
        self.relu = nn.ReLU()
        self.bn = nn.BatchNorm3d(out_ch)
        self.conv2 = nn.Conv3d(out_ch, out_ch, kernel_size, padding=1)
    
    def forward(self, x):
        return self.bn(self.relu(self.conv2(self.bn(self.relu(self.conv1(x))))))
    
class Encoder(nn.Module):
    def __init__(self, chs=(1, 32, 64, 128, 256, 512, 1024)):
        super().__init__()
        self.enc_blocks = nn.ModuleList([Block(chs[i], chs[i + 1]) for i in range(len(chs) - 1)])
        self.pool = nn.MaxPool3d(2)
    
    def forward(self, x):
        ftrs = []
        for block in self.enc_blocks:
            x = block(x)
            ftrs.append(x)
            x = self.pool(x)
        return ftrs
    
class Decoder(nn.Module):
    def __init__(self, chs=(1024, 512, 256, 128, 64, 32)):
        super().__init__()
        self.chs = chs
        self.upconvs = nn.ModuleList([nn.ConvTranspose3d(chs[i], chs[i + 1], 2, 2) for i in range(len(chs) - 1)])
        self.dec_blocks = nn.ModuleList([Block(chs[i], chs[i + 1]) for i in range(len(chs) - 1)])
        
    def forward(self, x, encoder_features):
        for i in range(len(self.chs) - 1):
            x = self.upconvs[i](x)
            x = torch.cat([x, encoder_features[i]], dim=1)
            x = self.dec_blocks[i](x)
        return x
    
class UNet(nn.Module):
    def __init__(self, enc_chs=(1, 32, 64, 128, 256, 512, 1024),
                 dec_chs=(1024, 512, 256, 128, 64, 32),
                 num_class=7,
                 out_sz=(64, 64, 64)):
        super().__init__()
        self.encoder = Encoder(enc_chs)
        self.decoder = Decoder(dec_chs)
        self.head = nn.Conv3d(dec_chs[-1], num_class, 1)
        
    def forward(self, x):
        enc_ftrs = self.encoder(x)
        out = self.decoder(enc_ftrs[::-1][0], enc_ftrs[::-1][1:])
        out = self.head(out)

        return out
        
class KITSModel(pl.LightningModule):

    def __init__(self,
                 net,
                 criterion=monai.losses.DiceCELoss(softmax=True),
                 learning_rate=1e-4,
                 optimizer_class=torch.optim.Adam):
        super().__init__()

        self.net = net
        self.lr = learning_rate
        self.criterion = criterion
        self.optimizer_class = optimizer_class
        
        self.example_input_array = torch.randn(1, 1, 64, 64, 64)
        
    def forward(self, x):
        return self.net(x)
    
    def configure_optimizers(self):
        optimizer = self.optimizer_class(self.parameters(), lr=self.lr)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, 50000)
        return [optimizer], [scheduler]
    
    def prepare_batch(self, batch):
        return batch['image'][tio.DATA], batch['label'][tio.DATA]
    
    def infer_batch(self, batch):
        x, y = self.prepare_batch(batch)
        y_hat = self.net(x)
        return y_hat, y, x

    def training_step(self, batch, batch_idx):
        y_hat, y, x = self.infer_batch(batch)
        loss = self.criterion(y_hat, y)
        self.log('Loss/Train', loss, prog_bar=True, on_step=True, on_epoch=False)
        
        if batch_idx % 100 == 0:
            monai.visualize.img2tensorboard.plot_2d_or_3d_image(x, batch_idx, self.logger.experiment, tag="Train/ct")
            monai.visualize.img2tensorboard.plot_2d_or_3d_image(
                torch.argmax(y_hat, dim=1, keepdim=True),
                batch_idx, self.logger.experiment, tag="Train/pred")
            monai.visualize.img2tensorboard.plot_2d_or_3d_image(
                torch.argmax(y, dim=1, keepdim=True),
                batch_idx, self.logger.experiment, tag="Train/gt")
        
        return loss
    
    def validation_step(self, batch, batch_idx):
        y_hat, y, x = self.infer_batch(batch)
        loss = self.criterion(y_hat, y)
        self.log('Loss/Val', loss, on_step=False, on_epoch=True)
        
        if batch_idx % 100 == 0:
            monai.visualize.img2tensorboard.plot_2d_or_3d_image(x, batch_idx, self.logger.experiment, tag="Val/ct")
            monai.visualize.img2tensorboard.plot_2d_or_3d_image(
                torch.argmax(y_hat, dim=1, keepdim=True),
                batch_idx, self.logger.experiment, tag="Val/pred")
            monai.visualize.img2tensorboard.plot_2d_or_3d_image(
                torch.argmax(y, dim=1, keepdim=True),
                batch_idx, self.logger.experiment, tag="Val/gt")
        
        return loss
    
    def test_step(self, batch, batch_idx):
        self.logger.log_graph(self, input_array=self.example_input_array)
```

the scenario:

```python
if __name__ == "__main__":
    
    torch.cuda.empty_cache()
    
    path = Path("/DATA/kits21") / "data"
    data = KitsDataModule(path)
    
    model = KITSModel(
        net=UNet(),
        criterion=monai.losses.DiceCELoss(softmax=True),
        learning_rate=1e-4,
        optimizer_class=torch.optim.Adam,
    )
    early_stopping = pl.callbacks.early_stopping.EarlyStopping(
        monitor='Loss/Val',
    )
    lr_monitor = LearningRateMonitor(logging_interval='epoch')
    logger = TensorBoardLogger("tb_logs", name="unet3D", log_graph=True, default_hp_metric=False)
    trainer = pl.Trainer(
        gpus=1,
        precision=32,
        callbacks=[
            #early_stopping,
            lr_monitor],
        logger=logger,
        max_steps=50000,
        num_sanity_val_steps=0
    )
    trainer.fit(model=model, datamodule=data)
```

**Expected behavior**

the training would be done without trouble

**Actual behavior**

the trainer crash after some epochs

```python-traceback
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type       | Params | In sizes           | Out sizes         
-----------------------------------------------------------------------------------
0 | net       | UNet       | 90.5 M | [1, 1, 64, 64, 64] | [1, 7, 64, 64, 64]
1 | criterion | DiceCELoss | 0      | ?                  | ?                 
-----------------------------------------------------------------------------------
90.5 M    Trainable params
0         Non-trainable params
90.5 M    Total params
361.922   Total estimated model params size (MB)
/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Epoch 5:  23%|██████████████████▊                                                                | 39/172 [07:59<27:16, 12.30s/it, loss=2.31, v_num=0, Loss/Train=2.080]
Traceback (most recent call last):                                                                                                                                      
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 7197) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ameyer/DEV/kits21/src/models/unet.py", line 113, in <module>
    trainer.fit(model=model, datamodule=data)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 484, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/profiler/profilers.py", line 82, in profile_iterable
    value = next(iterator)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 48, in _with_is_last
    for val in it:
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/trainer/supporters.py", line 470, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/trainer/supporters.py", line 484, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/pytorch_lightning/utilities/apply_func.py", line 84, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 165, in __getitem__
    self._fill()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 229, in _fill
    subject = self._get_next_subject()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torchio/data/queue.py", line 239, in _get_next_subject
    subject = next(self.subjects_iterable)
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 7197) exited unexpectedly
```

**System info**

Output of `python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)`:

```
Platform: Linux-5.4.0-73-generic-x86_64-with-debian-buster-sid
TorchIO:  0.18.39
PyTorch:  1.7.1
NumPy:    1.19.2
Python:   3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
[GCC 9.3.0]
```

**Comment by fepegar** [comment]
Hi, @Chop1. This error is related to PyTorch, not TorchIO: `/home/ameyer/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py`. You can open an issue on the `pytorch` repository. But they will probably ask you for a minimal working example (as we do here).

**Comment by fepegar** [comment]
Yeah I suspect it's a memory issue. I'd first try the same code but using `num_workers=0`. Error messages might become more helpful.
