### ISSUE TITLE
__len__ of the DataLoader raises an error for patch-based pipeline

### ISSUE THREAD

**Issue by hsiangyuzhao** [fepegar/torchio#564]
**🐛Bug**
Executing "len(dataloader)" throws an error.

**To reproduce**

```python
if is_patched:
    # if utilize patched training, use tio.Queue to generate random patches
    # note that attribute max_length is RAM demanding! Do not turn the value too large
    train_queue = tio.Queue(subjects_dataset=trainset,
                            max_length=max_length,
                            sampler=sampler,
                            samples_per_volume=samples_per_volume,
                            num_workers=2)
    # for queue training, num workers should be set to 0
    train_loader = DataLoader(train_queue, batch_size=batch_size, num_workers=0, pin_memory=False)
```

**Expected behavior**

returns the number of iterations in the dataloader

**Actual behavior**

```python-traceback
Traceback (most recent call last):
  File "<input>", line 89, in <module>
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 397, in __len__
    return len(self._index_sampler)
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 243, in __len__
    return (len(self.sampler) + self.batch_size - 1) // self.batch_size  # type: ignore
  File "/home/zhao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 70, in __len__
    return len(self.data_source)
TypeError: 'str' object cannot be interpreted as an integer
```

**System info**

Ubuntu 16.04, PyTorch 1.7.1+cu101, torchio 0.18.40

**Comment by hsiangyuzhao** [comment]
Sorry, it seems that is is just my own fault in the code. I will close the issue now.
