### ISSUE TITLE
error using RandomNoise and RandomBlur on 2D images

### ISSUE THREAD

**Issue by neuronflow** [fepegar/torchio#583]
**🐛Bug**
2d transform of my images is not working resulting in crash

**To reproduce**

I try to use torchio transforms on 2d sattelite images, I have only 1 input channel:

```python
# << INTENSITY augmentations >>
tio_intensity_prob = 0.2

_tio_noise_tfs = Compose([
    RandomBlur(p=tio_intensity_prob, keys=["images"]),
    RandomNoise(p=tio_intensity_prob, keys=["images"]),
])
```

**Expected behavior**
transformed images

**Actual behavior**
crash, I added dimensions and shape of the tensor to the error msg
```
Original Traceback (most recent call last):                                                                                          
  File "/home/florian/miniconda3/envs/sat/lib/python3.8/site-packages/monai/transforms/utils.py", line 361, in apply_transform       
    return transform(data)                                                                                                           
  File "/home/florian/miniconda3/envs/sat/lib/python3.8/site-packages/torchio/transforms/transform.py", line 68, in __call__         
    subject = data_parser.get_subject()                                                                                              
  File "/home/florian/miniconda3/envs/sat/lib/python3.8/site-packages/torchio/transforms/data_parser.py", line 66, in get_subject    
    subject = self._get_subject_from_dict(self.data, self.keys)                                                                      
  File "/home/florian/miniconda3/envs/sat/lib/python3.8/site-packages/torchio/transforms/data_parser.py", line 134, in _get_subject_$rom_dict
    value = ScalarImage(tensor=value)
  File "/home/florian/miniconda3/envs/sat/lib/python3.8/site-packages/torchio/data/image.py", line 516, in __init__
    super().__init__(*args, **kwargs)
  File "/home/florian/miniconda3/envs/sat/lib/python3.8/site-packages/torchio/data/image.py", line 124, in __init__
    tensor = self._parse_tensor(tensor)
  File "/home/florian/miniconda3/envs/sat/lib/python3.8/site-packages/torchio/data/image.py", line 364, in _parse_tensor
    raise ValueError(
ValueError: ('Input tensor must be 4D, but has these dimensions:', 3, torch.Size([1, 512, 512]))
```

**System info**

Output of `python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)`:

```
(sat) florian@ibbm_giga:~/satellite_one$ python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)
If you use TorchIO for your research, please cite the following paper:
Pérez-García et al., TorchIO: a Python library for efficient loading,
preprocessing, augmentation and patch-based sampling of medical images
in deep learning. Credits instructions: https://torchio.readthedocs.io/#credits

Platform: Linux-4.15.0-144-generic-x86_64-with-glibc2.10
TorchIO:  0.18.1
PyTorch:  1.7.0+cu110
NumPy:    1.18.1
Python:   3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
```

**Comment by fepegar** [comment]
```python-traceback
ValueError: ('Input tensor must be 4D, but has these dimensions:', 3, torch.Size([1, 512, 512]))
```

Please add a dummy dimension to your input tensors so they have shape `(1, 512, 512, 1)`.

**Comment by fepegar** [comment]
You can typically mix transforms from different frameworks. For example, you can code an `AddDimension` and a `Squeeze` transforms for this purpose. If you share more info about what you want to do, we can probably help.

**Comment by fepegar** [comment]
Did my suggestions solve your issues?

**Comment by neuronflow** [comment]
Yes, thank you. In the meantime I solved it like this with some MONAI transforms:
```
_tio_tfs = Compose([
    # we need to add and remove channel with Monai to use the torchio transforms
    AddChanneld(keys=only_images),
    _tio_noise_tfs,
    _tio_artefact_tfs,
    SqueezeDimd(keys=only_images)
])
```

I still believe "native" 2D support would be good enhancement :)

**Comment by fepegar** [comment]
What do you mean by "native 2D support"?

The challenge is that if a tensor with three dimensions is received, it is not clear if it's a 2D image with multiple components or a 3D image with a single component. Of course this could be solved using ITK always, but maybe that's a bit less user friendly, less "PyTorch", and too late for such a big change. That's why I decided to always go for 4D, so the meaning of each dimension is always the same. Hopefully, unsqueezing and squeezing is not too bad :)

**Comment by neuronflow** [comment]
Sorry, for the late response and thanks for clarifying :)
