### ISSUE TITLE
Numpy array of dtype uint16 gives an error

### ISSUE THREAD

**Issue by dmus** [fepegar/torchio#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

See reproducible example, the code tries to convert to a torch tensor before casting unsupported dtypes to supported dtypes

### Code for reproduction

```python
import torchio as tio
import numpy as np

tensor = np.random.rand(1, 32, 32, 32).astype(np.uint16)
test_path = 'test_image.npy'
np.save('test_image.npy', tensor)

numpy_reader = lambda path: (np.load(path), np.eye(4))  # Also note that the ( and ) are necessary. In the documentation example they are not there, then numpy reader is a tuple. That will produce another error
image = tio.ScalarImage(test_path, reader=numpy_reader)
image.load()
```

### Actual outcome

A TypeError is produced

### Error messages

```python-traceback
Traceback (most recent call last):
  File "reproduce.py", line 21, in <module>
    image.load()
  File "/home/derk/rndeep/venv/lib/python3.6/site-packages/torchio/data/image.py", line 507, in load
    tensor, affine = self.read_and_check(paths[0])
  File "/home/derk/rndeep/venv/lib/python3.6/site-packages/torchio/data/image.py", line 534, in read_and_check
    tensor = self._parse_tensor_shape(tensor)
  File "/home/derk/rndeep/venv/lib/python3.6/site-packages/torchio/data/image.py", line 459, in _parse_tensor_shape
    return ensure_4d(tensor)
  File "/home/derk/rndeep/venv/lib/python3.6/site-packages/torchio/data/io.py", line 404, in ensure_4d
    tensor = torch.as_tensor(tensor)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

### Expected outcome

I expect that the given example works

### System info

```shell
Platform:   Linux-5.4.0-62-generic-x86_64-with-Ubuntu-18.04-bionic
TorchIO:    0.18.70
PyTorch:    1.10.0+cu102
SimpleITK:  1.2.4 (ITK 4.13)
NumPy:      1.19.5
Python:     3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]
```

**Comment by fepegar** [comment]
Thanks for reporting, @dmus. I will add a more informative error and update the docs.

For now, you can quick-fix this using `check_uint_to_int`:

```python
def numpy_reader(path):
    data = tio.io.check_uint_to_int(np.load(path))
    affine = np.eye(4)
    return data, affine
```

**Comment by fepegar** [comment]
This should work in the next version. Also, thanks for pointing out the issue with the example.
