### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [1, 64, 64, 64] at entry 0 and [4, 64, 64, 64] at entry 3

### ISSUE THREAD

**Issue by ankitabuntolia** [fepegar/torchio#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

I am following [TorchIO Tutorial](https://colab.research.google.com/github/fepegar/torchio-notebooks/blob/main/notebooks/TorchIO_tutorial.ipynb#scrollTo=b0NdJiFW3Uy7) for my 3D OCT Image Segmentation task.

Background: All of my images and labels are of size 512x496x49 In the label I have 4 classes (including a background as 0 and all others are 1,2,3)

I am facing the error of size mismatch of tensor. this is from #848 

### Code for reproduction

```python
subjects_list = []
for i in range(len(data_dict)):
  subject_dict = {
    'image': tio.ScalarImage(data_dict[i]['image']),
    'label': tio.LabelMap(data_dict[i]['label'])}
  subject = tio.Subject(subject_dict)
  subjects_list.append(subject)
  
# historgram of all images
paths = image_paths
compute_histograms = 0

def plot_histogram(axis, tensor, num_positions=100, label=None, alpha=0.05, color=None):
    values = tensor.numpy().ravel()
    kernel = stats.gaussian_kde(values)
    positions = np.linspace(values.min(), values.max(), num=num_positions)
    histogram = kernel(positions)
    kwargs = dict(linewidth=1, color='black' if color is None else color, alpha=alpha)
    if label is not None:
        kwargs['label'] = label
    axis.plot(positions, histogram, **kwargs)

if compute_histograms:
    fig, ax = plt.subplots(dpi=100)
    for path in tqdm(paths):
        tensor = tio.ScalarImage(path).data
        # if 'IRF_CODE' in path.name: color = 'red'
        # elif 'SRF_CODE' in path.name: color = 'green'
        # elif 'PED_CODE' in path.name: color = 'blue'
        #plot_histogram(ax, tensor, color=color)
        plot_histogram(ax, tensor)
        
    ax.set_xlim(-100, 2000)
    ax.set_ylim(0, 0.004);
    ax.set_title('Original histograms of all samples')
    ax.set_xlabel('Intensity')
    ax.grid()
    graph = None
    fig.savefig('/content/drive/MyDrive/Practical_work/Report/code/Spectralis/torchIO/histogram_original.png')
else:
    graph = display.Image('/content/drive/MyDrive/Practical_work/Report/code/Spectralis/torchIO/histogram_original.png')
graph

landmarks = tio.HistogramStandardization.train(
    image_paths,
    output_path=histogram_landmarks_path,
)
np.set_printoptions(suppress=True, precision=3)
print('\nTrained landmarks:', landmarks)

landmarks_dict = {'image': landmarks}
histogram_transform = tio.HistogramStandardization(landmarks_dict)

compute_histograms = 0

if compute_histograms:
    fig, ax = plt.subplots(dpi=100)
    for i ,sample in enumerate(tqdm(subjects_dataset)):
        standard = histogram_transform(sample)
        tensor = standard.image.data
        path = str(sample.image.path)
        # if 'HH' in path: color = 'red'
        # elif 'Guys' in path: color = 'green'
        # elif 'IOP' in path: color = 'blue'
        # plot_histogram(ax, tensor, color=color)
        plot_histogram(ax, tensor)
        
    ax.set_xlim(0, 150)
    # ax.set_ylim(0, 0.02)
    ax.set_ylim(0, 0.08)
    ax.set_title('Intensity values of all samples after histogram standardization')
    ax.set_xlabel('Intensity')
    ax.grid()
    graph = None
    fig.savefig('/content/drive/MyDrive/Practical_work/Report/code/Spectralis/torchIO/histogram_std.png')
else:
    graph = display.Image('/content/drive/MyDrive/Practical_work/Report/code/Spectralis/torchIO/histogram_std.png')
graph

###
znorm_transform = tio.ZNormalization(masking_method=tio.ZNormalization.mean)

sample = subjects_dataset[0]
transform = tio.Compose([histogram_transform, znorm_transform])
znormed = transform(sample)

fig, ax = plt.subplots(dpi=100)
plot_histogram(ax, znormed.image.data, label='Z-normed', alpha=1)
ax.set_title('Intensity values of one sample after z-normalization')
ax.set_xlabel('Intensity')
ax.grid()

### Transform

training_transform = tio.Compose([
    tio.ToCanonical(),
    # tio.Resample(4),
    tio.CropOrPad((64, 64, 64)), # tuple: (W, H, D)
    # tio.RandomMotion(p=0.2),
    # tio.HistogramStandardization({'image': landmarks}),
    # tio.RandomBiasField(p=0.3),
    # tio.ZNormalization(masking_method=tio.ZNormalization.mean),
    # # tio.RandomNoise(p=0.5),
    # tio.RandomFlip(),
    # tio.OneOf({
    #     tio.RandomAffine(): 0.8,
        # tio.RandomElasticDeformation(max_displacement=2): 0.2,
    # }),
    tio.OneHot(),
])

validation_transform = tio.Compose([
    tio.ToCanonical(),
    # tio.Resample(4),
    tio.CropOrPad((64, 64, 64)),
    # tio.HistogramStandardization({'image': landmarks}),
    # tio.ZNormalization(masking_method=tio.ZNormalization.mean),
    tio.OneHot(),
])

num_subjects = len(subjects_dataset)
num_training_subjects = int(training_split_ratio * num_subjects)
num_validation_subjects = num_subjects - num_training_subjects

num_split_subjects = num_training_subjects, num_validation_subjects
training_subjects, validation_subjects = torch.utils.data.random_split(subjects_list, num_split_subjects)

training_set = tio.SubjectsDataset(
    training_subjects, transform=training_transform)

validation_set = tio.SubjectsDataset(
    validation_subjects, transform=validation_transform)

print('Training set:', len(training_set), 'subjects')
print('Validation set:', len(validation_set), 'subjects')

### 
device = torch.device('cuda') if torch.cuda.is_available() else 'cpu'
CHANNELS_DIMENSION = 1
SPATIAL_DIMENSIONS = 2, 3, 4

class Action(enum.Enum):
    TRAIN = 'Training'
    VALIDATE = 'Validation'

def prepare_batch(batch, device):
    inputs = batch['image'][tio.DATA].to(device)
    targets = batch['label'][tio.DATA].to(device)
    return inputs, targets

def get_dice_score(output, target, epsilon=1e-9):
    p0 = output
    g0 = target
    p1 = 1 - p0
    g1 = 1 - g0
    tp = (p0 * g0).sum(dim=SPATIAL_DIMENSIONS)
    fp = (p0 * g1).sum(dim=SPATIAL_DIMENSIONS)
    fn = (p1 * g0).sum(dim=SPATIAL_DIMENSIONS)
    num = 2 * tp
    denom = 2 * tp + fp + fn + epsilon
    dice_score = num / denom
    return dice_score

def get_dice_loss(output, target):
    return 1 - get_dice_score(output, target)

def get_model_and_optimizer(device):
  # https://github.com/fepegar/unet/blob/master/unet/unet.py
    model = UNet(
        in_channels=1,
        out_classes=3,
        dimensions=3,
        num_encoding_blocks=4,
        out_channels_first_layer=32,
        normalization='batch',
        upsampling_type='bilinear',
        padding=True,
        activation='PReLU',
    ).to(device)
    optimizer = torch.optim.AdamW(model.parameters())
    return model, optimizer

# model = monai.networks.nets.UNet(
#     spatial_dims=3,
#     in_channels=1,
#     out_channels=3,
#     channels=(8, 16, 32, 64, 128),
#     strides=(2, 2, 2, 2),
#     ).to(device)

# optimizer = torch.optim.AdamW(model.parameters())

def run_epoch(epoch_idx, action, loader, model, optimizer):
    is_training = action == Action.TRAIN
    epoch_losses = []
    times = []
    model.train(is_training)
    for batch_idx, batch in enumerate(tqdm(loader)):
        inputs, targets = prepare_batch(batch, device)
        optimizer.zero_grad()
        with torch.set_grad_enabled(is_training):
            logits = model(inputs)
            probabilities = F.softmax(logits, dim=CHANNELS_DIMENSION)
            batch_losses = get_dice_loss(probabilities, targets)
            batch_loss = batch_losses.mean()
            if is_training:
                batch_loss.backward()
                optimizer.step()
            times.append(time.time())
            epoch_losses.append(batch_loss.item())
    epoch_losses = np.array(epoch_losses)
    print(f'{action.value} mean loss: {epoch_losses.mean():0.3f}')
    return times, epoch_losses

def train(num_epochs, training_loader, validation_loader, model, optimizer, weights_stem):
    train_losses = []
    val_losses = []
    val_losses.append(run_epoch(0, Action.VALIDATE, validation_loader, model, optimizer))
    for epoch_idx in range(1, num_epochs + 1):
        print('Starting epoch', epoch_idx)
        train_losses.append(run_epoch(epoch_idx, Action.TRAIN, training_loader, model, optimizer))
        val_losses.append(run_epoch(epoch_idx, Action.VALIDATE, validation_loader, model, optimizer))
        torch.save(model.state_dict(), f'{weights_stem}_epoch_{epoch_idx}.pth')
    return np.array(train_losses), np.array(val_losses)

### Dataloader
training_batch_size = 16
validation_batch_size = 2 * training_batch_size

training_loader = torch.utils.data.DataLoader(
    training_set,
    batch_size=training_batch_size,
    shuffle=True,
    num_workers=num_workers,
)

validation_loader = torch.utils.data.DataLoader(
    validation_set,
    batch_size=validation_batch_size,
    num_workers=num_workers,
)

## Training
num_epochs = 10
train_whole_images = 1

model, optimizer = get_model_and_optimizer(device)

weights_path = '/content/drive/MyDrive/Practical_work/Report/code/Spectralis/torchIO/whole_image_state_dict.pth'
if train_whole_images:
    weights_stem = 'whole_images'
    train_losses, val_losses = train(num_epochs, training_loader, validation_loader, model, optimizer, weights_stem)
    checkpoint = {
        'train_losses': train_losses,
        'val_losses': val_losses,
        'weights': model.state_dict(),
    }
    torch.save(checkpoint, weights_path)
else:
    weights_path = 'whole_image_state_dict.pth'
    weights_url = 'https://github.com/fepegar/torchio-data/raw/master/models/whole_images_epoch_5.pth'
    !curl --location --silent --output {weights_path} {weights_url}
    checkpoint = torch.load(weights_path)
    model.load_state_dict(checkpoint['weights'])
    train_losses, val_losses = checkpoint['train_losses'], checkpoint['val_losses']

def plot_times(axis, losses, label):
    from datetime import datetime
    times, losses = losses.transpose(1, 0, 2)
    times = [datetime.fromtimestamp(x) for x in times.flatten()]
    axis.plot(times, losses.flatten(), label=label)
    
fig, ax = plt.subplots()
plot_times(ax, train_losses, 'Training')
plot_times(ax, val_losses, 'Validation')
ax.grid()
ax.set_xlabel('Time')
ax.set_ylabel('Dice loss')
ax.set_title('Training with whole images')
ax.legend()
fig.autofmt_xdate()

#############
Here it is throwing tensor size mismatch error
```

### Actual outcome

Currently it is throwing error

### Error messages

```python-traceback
0%
0/1 [00:02<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-47-548ff268452a> in <module>()
     20 if train_whole_images:
     21     weights_stem = 'whole_images'
---> 22     train_losses, val_losses = train(num_epochs, training_loader, validation_loader, model, optimizer, weights_stem)
     23     checkpoint = {
     24         'train_losses': train_losses,

7 frames
/usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self)
    432             # instantiate since we don't know how to
    433             raise RuntimeError(msg) from None
--> 434         raise exception
    435 
    436 

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 64, 64, 64] at entry 0 and [4, 64, 64, 64] at entry 2
```

### Expected outcome

It should do training

### System info

```shell
### I am running my code on Google colab noteboook, Here is the output of this command from colab:

# flake8: noqa

import re
import sys
import platform
import torchio
import torch
import numpy
import SimpleITK as sitk


sitk_version = re.findall('SimpleITK Version: (.*?)\n', str(sitk.Version()))[0]

print('Platform:  ', platform.platform())
print('TorchIO:   ', torchio.__version__)
print('PyTorch:   ', torch.__version__)
print('SimpleITK: ', sitk_version)
print('NumPy:     ', numpy.__version__)
print('Python:    ', sys.version)
```

**Comment by ankitabuntolia** [comment]
Hello, @snipdome could you please help me to resolve this issue? 
(@fepegar asked me to file this bug)

**Comment by fepegar** [comment]
Hi, @ankitabuntolia. It's not clear from the code you've shared that the error is caused by TorchIO. Please try to write a _minimal reproducible example_ and open a new issue if you like.
