### ISSUE TITLE
Multiprocessing doesn't work on Ubuntu 20.04 with 3090?

### ISSUE THREAD

**Issue by melhzy** [fepegar/torchio#945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

I am using Medical Segmentation Decatholon's Task03_Liver.tar data (https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2) to run my 3D-UNet algorithm.
Single GPU (3090) works, but multiple GPUs (3090) do not work and generated me the error message listed below.

### Code for reproduction

```python
model = Segmenter()

trainer = pl.Trainer(accelerator="gpu", devices = -1,
                     logger=TensorBoardLogger(save_dir="./logs"), 
                     log_every_n_steps=1,
                     callbacks=checkpoint_callback,
                     max_epochs=10)
trainer.fit(model, train_loader, val_loader)
```

### Actual outcome

I want to train the 3D-UNet using multiple 3090s.

### Error messages

```python-traceback
> GPU available: True (cuda), used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
> Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
> Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
> Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4

----------------------------------------------------------------------------------------------------

> distributed_backend=nccl
> All distributed processes registered. Starting with 4 processes

----------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
<ipython-input-31-42a7f08aa10a> in <module>
      8                      callbacks=checkpoint_callback,
      9                      max_epochs=10)
---> 10 trainer.fit(model, train_loader, val_loader)

~/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    698         """
    699         self.strategy.model = model
--> 700         self._call_and_handle_interrupt(
    701             self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    702         )

~/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    650         try:
    651             if self.strategy.launcher is not None:
--> 652                 return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
    653             else:
    654                 return trainer_fn(*args, **kwargs)

~/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py in launch(self, function, trainer, *args, **kwargs)
    101             process_args = [trainer, function, args, kwargs, return_queue]
    102 
--> 103         mp.start_processes(
    104             self._wrapping_function,
    105             args=process_args,

~/anaconda3/envs/net-opt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    196 
    197     # Loop on join until it returns True or raises an exception.
--> 198     while not context.join():
    199         pass
    200 

~/anaconda3/envs/net-opt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    158         msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    159         msg += original_trace
--> 160         raise ProcessRaisedException(msg, error_index, failed_process.pid)
    161 
    162 

ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 129, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1101, in _run
    self.strategy.setup_environment()
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 130, in setup_environment
    self.accelerator.setup_environment(self.root_device)
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/pytorch_lightning/accelerators/cuda.py", line 43, in setup_environment
    torch.cuda.set_device(root_device)
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/zi/anaconda3/envs/net-opt/lib/python3.8/site-packages/torch/cuda/__init__.py", line 207, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

### Expected outcome

I should be able to train the 3D-UNet segmentation.

### System info

```shell
Platform:   Linux-5.15.0-43-generic-x86_64-with-glibc2.17
TorchIO:    0.18.84
PyTorch:    1.12.0
SimpleITK:  2.1.0 (ITK 5.2)
NumPy:      1.23.1
Python:     3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]
```

**Comment by fepegar** [comment]
Hi, @melhzy. This seems unrelated to TorchIO. I suggest you ask in the PyTorch Lightning GitHub repo.
