### ISSUE TITLE
CropOrPad with marginally different Origins

### ISSUE THREAD

**Issue by mwyburd** [fepegar/torchio#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

I am trying to Crop or Pad using "tio.transforms.CropOrPad" around a segmentation label from the CT Decatholon Liver dataset, however, when I load in the image and corresponding label, the two images have very slightly different origins so the function fails. Is there anyway around this? 

image origin:  (-197.1123046875, -27.1123046875, -1114.0999755859375) 
label  origin: (-197.11260986328125, -27.112300872802734, -1114.0999755859375)

### Code for reproduction

```python
import torchio as tio
import torch


class TorchioPreprocessing():

    def __init__(self,spacing,fin_size) -> None:
        pass
        # Torchio Transformation
        self.pad_crop = tio.transforms.CropOrPad(fin_size,mask_name='label')


prep = TorchioPreprocessing(spacing=(3,3,3),fin_size=(112,112,112))
id = 2
# Paths to dataset
lab_path = f"labelsTr/liver_{id}.nii.gz"
img_path = f"imagesTr/liver_{id}_0000.nii.gz"

 # 1. Gen a tio Subject:
subject = tio.Subject(image=tio.Image(path=img_path,type="intensity"), label =tio.LabelMap(path=lab_path))

print('image ',subject['image'].origin ,'label ',subject['label'].origin )

# 2. Pad Or Crop to our desired size
subject=prep.pad_crop(subject)
```

### Actual outcome

It crashes during pad and crop as the origin differs

### Error messages

```python-traceback
image  (-197.1123046875, -27.1123046875, -1114.0999755859375) label  (-197.11260986328125, -27.112300872802734, -1114.0999755859375)
Traceback (most recent call last):
  File "/home/X/miniconda3/envs/Con3/lib/python3.7/site-packages/torchio/data/subject.py", line 311, in check_consistent_space
    self.check_consistent_attribute('origin')
  File "/home/X/miniconda3/envs/Con3/lib/python3.7/site-packages/torchio/data/subject.py", line 287, in check_consistent_attribute
    raise RuntimeError(message)
RuntimeError: More than one value for "origin" found in subject images:
{'image': (-197.1123046875, -27.1123046875, -1114.0999755859375),
 'label': (-197.11260986328125, -27.112300872802734, -1114.0999755859375)}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/DATA/DATA/Decath_liver/scripts_Oct22/ProcessLiver.py", line 57, in <module>
    subject=prep.pad_crop(subject)
  File "/home/X/miniconda3/envs/Con3/lib/python3.7/site-packages/torchio/transforms/transform.py", line 158, in __call__
    transformed = self.apply_transform(subject)
  File "/home/X/miniconda3/envs/Con3/lib/python3.7/site-packages/torchio/transforms/preprocessing/spatial/crop_or_pad.py", line 278, in apply_transform
    subject.check_consistent_space()
  File "/home/X/miniconda3/envs/Con3/lib/python3.7/site-packages/torchio/data/subject.py", line 320, in check_consistent_space
    raise RuntimeError(message) from e
RuntimeError: As described above, some images in the subject are not in the same space. You probably can use the transforms ToCanonical and Resample to fix this, as explained at https://github.com/fepegar/torchio/issues/647#issuecomment-913025695
```

### Expected outcome

N/A

### System info

```shell
Platform:   Linux-5.15.7-arch1-1-x86_64-with-arch
TorchIO:    0.18.84
PyTorch:    1.11.0+cu102
SimpleITK:  1.2.2 (ITK 4.13)
NumPy:      1.21.6
Python:     3.7.3 (default, Mar 27 2019, 22:11:17)
```

**Comment by mwyburd** [comment]
Thanks for getting back to me so quickly! That's fixed it :)
